version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: minhha-backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=development
      - CORS_ORIGINS=["http://localhost:12000","http://frontend:12000","*"]
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    networks:
      - minhha-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: minhha-frontend
    ports:
      - "12000:12000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - PORT=12000
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - minhha-network
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: minhha-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - minhha-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  minhha-network:
    driver: bridge

volumes:
  backend-data:
  frontend-data: